name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./cloud-flask-task2
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and run pylint
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pylint flasktask2.py
        
